### ISSUE TITLE
Css transitions are jittery on a:hover

### ISSUE THREAD

**Issue by mantagen** [ronanyeah/home#40]
This is due to padding on hover, but no padding in default state

**Comment by nelsonic** [comment]
@mantagen what page are you seeing the jittery transitions on? the homepage? 🤔

**Comment by mantagen** [comment]
@nelsonic Yes homepage. Eg hover over <script></script> in bottom left corner, there is a transition to make the background black, then when the transition is complete, padding is added. This detracts from the smoothness of the transition IMHO.

**Comment by nelsonic** [comment]
@mantagen _confirmed_. 👍 
Mac. OSX 10.12.2 Running Chrome v58.
Hovering over the `<script></script>` the text _appears_ to move 3px to the right.
![output_7yfers](https://cloud.githubusercontent.com/assets/194400/22358262/8e786294-e435-11e6-9a8d-992f5506b846.gif)
Could it be an "_optical illusion_"...? (IDK!)

**Comment by ronanyeah** [comment]
https://github.com/ronanyeah/home/commit/d51de601ebba1e205e711c5a472a47d792372978
