### ISSUE TITLE
replace joi w/ revalidate

### ISSUE THREAD

**Issue by ronanyeah** [ronanyeah/home#41]
http://revalidate.jeremyfairbank.com/

**Comment by nelsonic** [comment]
revalidate looks good! 👍 
![revalidate](https://cloud.githubusercontent.com/assets/194400/22824599/7a0d26d6-ef80-11e6-8374-3f83c2bd88e6.png)

_curious_ what the "_issue_" is you are facing with `joi`...? 🤔  ❓

**Comment by ronanyeah** [comment]
i LOVE composition, and revalidate seems to have that at the forefront. also i've always felt that joi was too verbose and ugly for my liking.

yeah using it once on this server but i have a product in development that will need schema validation everywhere, and the server is heavily based on this one. no function bodies so far!!

**Comment by ronanyeah** [comment]
no APM or anything like that so far.

**Comment by ronanyeah** [comment]
well, technically no function 'block bodies'... not pointfree yet...
